/* Automatically generated by './build/entry.js' */
import Tabbar from '../packages/Tabbar/index.js'
import Demo from '../packages/demo/index.js'

const components = [Tabbar, Demo]

const install = function (Vue) {
  components.forEach((component) => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  // components
  Tabbar,
  Demo
}

export default {
  install,
  Tabbar,
  Demo
}
